version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trip-api-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
