version: '3.8'

services:
  trip-api-container:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M